#version 460
struct _GLF_struct_3 {
 mat2x3 _f0;
} ;

struct _GLF_struct_2 {
 uvec4 _f0;
 mat4x2 _f1;
 ivec3 _f2;
 mat3x4 _f3;
 mat2x4 _f4;
 uvec4 _f5;
} ;

struct _GLF_struct_1 {
 mat3 _f0;
 mat2x3 _f1;
 mat3 _f2;
 ivec4 _f3;
 ivec3 _f4;
 mat2x3 _f5;
} ;

struct _GLF_struct_4 {
 bvec2 _f0;
 _GLF_struct_1 _f1;
 uint virtual_gid;
 _GLF_struct_2 _f2;
 _GLF_struct_3 _f3;
} ;

struct _GLF_struct_5 {
 mat3 _f0;
 _GLF_struct_4 _f1;
} ;

struct _GLF_struct_0 {
 ivec3 _f0;
 uint next_virtual_gid;
 bvec4 _f1;
} ;

layout(set = 0, binding = 0) uniform buf0 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf;
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec2 GLF_merged2_0_1_17_1_1_13subgroup_local_idsubgroup_size;
 uint subgroup_id = gl_SubgroupID;
 uint subgroup_size = 16;
 GLF_merged2_0_1_17_1_1_13subgroup_local_idsubgroup_size.y = subgroup_size;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 GLF_merged2_0_1_17_1_1_13subgroup_local_idsubgroup_size.x = subgroup_local_id;
 uint num_workgroup = gl_NumWorkGroups.x;
 uint workgroup_size = gl_WorkGroupSize.x;
 uint workgroup_id = gl_WorkGroupID.x;
 uint workgroup_base = workgroup_size * workgroup_id;
 _GLF_struct_5 _GLF_struct_replacement_5 = _GLF_struct_5(mat3(1.0), _GLF_struct_4(bvec2(true), _GLF_struct_1(mat3(1.0), mat2x3(1.0), mat3(1.0), ivec4(1), ivec3(1), mat2x3(1.0)), workgroup_base + subgroup_id * GLF_merged2_0_1_17_1_1_13subgroup_local_idsubgroup_size.y + GLF_merged2_0_1_17_1_1_13subgroup_local_idsubgroup_size.x, _GLF_struct_2(uvec4(1u), mat4x2(1.0), ivec3(1), mat3x4(1.0), mat2x4(1.0), uvec4(1u)), _GLF_struct_3(mat2x3(1.0))));
 _GLF_struct_0 _GLF_struct_replacement_0 = _GLF_struct_0(ivec3(1), workgroup_base + subgroup_id * GLF_merged2_0_1_17_1_1_13subgroup_local_idsubgroup_size.y + ((GLF_merged2_0_1_17_1_1_13subgroup_local_idsubgroup_size.x + 1) % GLF_merged2_0_1_17_1_1_13subgroup_local_idsubgroup_size.y), bvec4(true));
 buf = _GLF_struct_replacement_5._f1.virtual_gid;
 subgroupAllEqual(buf);
}
