#version 460
struct _GLF_struct_34 {
 vec3 _f0;
 bvec2 _f1;
} ;

struct _GLF_struct_33 {
 bvec4 _f0;
 float _f1;
 uvec2 _f2;
 bvec3 _f3;
 ivec3 _f4;
} ;

struct _GLF_struct_35 {
 uvec2 _f0;
 mat3x2 _f1;
 mat2x4 _f2;
 uint total_threads;
 _GLF_struct_33 _f3;
 _GLF_struct_34 _f4;
} ;

struct _GLF_struct_31 {
 mat2x4 _f0;
} ;

struct _GLF_struct_30 {
 float _f0;
 mat4x2 _f1;
} ;

struct _GLF_struct_32 {
 uvec3 _f0;
 _GLF_struct_30 _f1;
 _GLF_struct_31 _f2;
} ;

struct _GLF_struct_36 {
 bvec2 _f0;
 _GLF_struct_32 _f1;
 mat4x2 _f2;
 mat2 _f3;
 mat2 _f4;
 _GLF_struct_35 _f5;
 int _f6;
} ;

struct _GLF_struct_27 {
 mat3x2 _f0;
 uvec2 _f1;
 mat2 _f2;
 mat3x2 _f3;
} ;

struct _GLF_struct_26 {
 mat4 _f0;
 uvec3 _f1;
 bvec2 _f2;
 bvec3 _f3;
 ivec3 _f4;
 uvec3 _f5;
} ;

struct _GLF_struct_28 {
 _GLF_struct_26 _f0;
 _GLF_struct_27 _f1;
} ;

struct _GLF_struct_25 {
 uint subgroup_size;
 mat2x3 _f0;
} ;

struct _GLF_struct_29 {
 _GLF_struct_25 _f0;
 mat4x3 _f1;
 mat4x2 _f2;
 int _f3;
 bool _f4;
 _GLF_struct_28 _f5;
 uvec3 _f6;
} ;

struct _GLF_struct_22 {
 mat2x3 _f0;
} ;

struct _GLF_struct_23 {
 _GLF_struct_22 _f0;
 float _f1;
 mat4 _f2;
} ;

struct _GLF_struct_21 {
 bvec2 _f0;
 uvec3 _f1;
} ;

struct _GLF_struct_24 {
 mat2x3 _f0;
 _GLF_struct_21 _f1;
 _GLF_struct_23 _f2;
 uvec3 _f3;
 uint workgroup_size;
 mat4 _f4;
} ;

struct _GLF_struct_18 {
 vec2 _f0;
 mat2 _f1;
 mat3x4 _f2;
 mat2 _f3;
} ;

struct _GLF_struct_19 {
 vec4 _f0;
 _GLF_struct_18 _f1;
} ;

struct _GLF_struct_16 {
 mat2x4 _f0;
 bool _f1;
 mat2 _f2;
} ;

struct _GLF_struct_15 {
 mat3x2 _f0;
 float _f1;
 float _f2;
} ;

struct _GLF_struct_14 {
 uvec3 _f0;
 mat4x2 _f1;
 mat3x2 _f2;
 mat3x4 _f3;
 uvec2 _f4;
} ;

struct _GLF_struct_17 {
 _GLF_struct_14 _f0;
 _GLF_struct_15 _f1;
 _GLF_struct_16 _f2;
} ;

struct _GLF_struct_20 {
 vec4 _f0;
 float _f1;
 _GLF_struct_17 _f2;
 uint num_workgroup;
 bvec3 _f3;
 _GLF_struct_19 _f4;
} ;

struct _GLF_struct_11 {
 mat4x2 _f0;
 float _f1;
 uint _f2;
 bvec3 _f3;
 mat4x3 _f4;
 mat2x4 _f5;
} ;

struct _GLF_struct_10 {
 ivec3 _f0;
 bvec3 _f1;
 int _f2;
} ;

struct _GLF_struct_12 {
 uvec3 _f0;
 _GLF_struct_10 _f1;
 _GLF_struct_11 _f2;
 bool _f3;
} ;

struct _GLF_struct_8 {
 bvec2 _f0;
 mat3x4 _f1;
 bvec2 _f2;
} ;

struct _GLF_struct_7 {
 vec3 _f0;
 mat2 _f1;
 uvec3 _f2;
 uvec3 _f3;
 uvec2 _f4;
 mat3 _f5;
} ;

struct _GLF_struct_9 {
 _GLF_struct_7 _f0;
 bvec3 _f1;
 vec4 _f2;
 mat2 _f3;
 _GLF_struct_8 _f4;
} ;

struct _GLF_struct_6 {
 mat4 _f0;
} ;

struct _GLF_struct_4 {
 uvec3 _f0;
 bvec4 _f1;
 bool _f2;
 uvec3 _f3;
 uvec3 _f4;
} ;

struct _GLF_struct_5 {
 _GLF_struct_4 _f0;
} ;

struct _GLF_struct_2 {
 mat3 _f0;
 ivec4 _f1;
 mat3x4 _f2;
 vec2 _f3;
 mat4x2 _f4;
 vec4 _f5;
} ;

struct _GLF_struct_1 {
 bvec2 _f0;
 bvec2 _f1;
} ;

struct _GLF_struct_3 {
 vec2 _f0;
 _GLF_struct_1 _f1;
 _GLF_struct_2 _f2;
 mat2 _f3;
} ;

struct _GLF_struct_13 {
 uvec4 _f0;
 _GLF_struct_3 _f1;
 ivec2 _f2;
 _GLF_struct_5 _f3;
 _GLF_struct_6 _f4;
 _GLF_struct_9 _f5;
 _GLF_struct_12 _f6;
 uint subgroup_local_id;
} ;

struct _GLF_struct_0 {
 mat4x2 _f0;
 uint gid;
} ;

layout(set = 0, binding = 0) uniform buf0 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uint subgroup_id = gl_SubgroupID;
 _GLF_struct_29 _GLF_struct_replacement_29 = _GLF_struct_29(_GLF_struct_25(gl_SubgroupSize, mat2x3(1.0)), mat4x3(1.0), mat4x2(1.0), 1, true, _GLF_struct_28(_GLF_struct_26(mat4(1.0), uvec3(1u), bvec2(true), bvec3(true), ivec3(1), uvec3(1u)), _GLF_struct_27(mat3x2(1.0), uvec2(1u), mat2(1.0), mat3x2(1.0))), uvec3(1u));
 _GLF_struct_0 _GLF_struct_replacement_0 = _GLF_struct_0(mat4x2(1.0), gl_GlobalInvocationID.x);
 _GLF_struct_13 _GLF_struct_replacement_13 = _GLF_struct_13(uvec4(1u), _GLF_struct_3(vec2(1.0), _GLF_struct_1(bvec2(true), bvec2(true)), _GLF_struct_2(mat3(1.0), ivec4(1), mat3x4(1.0), vec2(1.0), mat4x2(1.0), vec4(1.0)), mat2(1.0)), ivec2(1), _GLF_struct_5(_GLF_struct_4(uvec3(1u), bvec4(true), true, uvec3(1u), uvec3(1u))), _GLF_struct_6(mat4(1.0)), _GLF_struct_9(_GLF_struct_7(vec3(1.0), mat2(1.0), uvec3(1u), uvec3(1u), uvec2(1u), mat3(1.0)), bvec3(true), vec4(1.0), mat2(1.0), _GLF_struct_8(bvec2(true), mat3x4(1.0), bvec2(true))), _GLF_struct_12(uvec3(1u), _GLF_struct_10(ivec3(1), bvec3(true), 1), _GLF_struct_11(mat4x2(1.0), 1.0, 1u, bvec3(true), mat4x3(1.0), mat2x4(1.0)), true), gl_SubgroupInvocationID);
 _GLF_struct_20 _GLF_struct_replacement_20 = _GLF_struct_20(vec4(1.0), 1.0, _GLF_struct_17(_GLF_struct_14(uvec3(1u), mat4x2(1.0), mat3x2(1.0), mat3x4(1.0), uvec2(1u)), _GLF_struct_15(mat3x2(1.0), 1.0, 1.0), _GLF_struct_16(mat2x4(1.0), true, mat2(1.0))), gl_NumWorkGroups.x, bvec3(true), _GLF_struct_19(vec4(1.0), _GLF_struct_18(vec2(1.0), mat2(1.0), mat3x4(1.0), mat2(1.0))));
 _GLF_struct_24 _GLF_struct_replacement_24 = _GLF_struct_24(mat2x3(1.0), _GLF_struct_21(bvec2(true), uvec3(1u)), _GLF_struct_23(_GLF_struct_22(mat2x3(1.0)), 1.0, mat4(1.0)), uvec3(1u), gl_WorkGroupSize.x, mat4(1.0));
 _GLF_struct_36 _GLF_struct_replacement_36 = _GLF_struct_36(bvec2(true), _GLF_struct_32(uvec3(1u), _GLF_struct_30(1.0, mat4x2(1.0)), _GLF_struct_31(mat2x4(1.0))), mat4x2(1.0), mat2(1.0), mat2(1.0), _GLF_struct_35(uvec2(1u), mat3x2(1.0), mat2x4(1.0), _GLF_struct_replacement_20.num_workgroup * _GLF_struct_replacement_24.workgroup_size, _GLF_struct_33(bvec4(true), 1.0, uvec2(1u), bvec3(true), ivec3(1)), _GLF_struct_34(vec3(1.0), bvec2(true))), 1);
 if(_GLF_struct_replacement_13.subgroup_local_id + 1 < _GLF_struct_replacement_29._f0.subgroup_size)
  {
   atomicStore(buf[(_GLF_struct_replacement_0.gid + 1) % _GLF_struct_replacement_36._f5.total_threads], uint(2), 4, 64, 4);
   subgroupAll(false);
  }
 else
  {
   atomicStore(buf[(_GLF_struct_replacement_0.gid + 1) % _GLF_struct_replacement_36._f5.total_threads], uint(2), 4, 64, 4);
   subgroupAll(true);
  }
}
