#version 460
struct _GLF_struct_0 {
 uvec3 _f0;
 vec4 _f1;
 bvec3 _f2;
 mat4x2 _f3;
} ;

struct _GLF_struct_1 {
 _GLF_struct_0 _f0;
 vec4 _f1;
 mat3 _f2;
 uint subgroup_size;
} ;

struct _GLF_struct_2 {
 vec4 _f0;
 _GLF_struct_1 _f1;
} ;

layout(set = 0, binding = 1) uniform buf1 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uint subgroup_id = gl_SubgroupID;
 _GLF_struct_2 _GLF_struct_replacement_2 = _GLF_struct_2(vec4(1.0), _GLF_struct_1(_GLF_struct_0(uvec3(1u), vec4(1.0), bvec3(true), mat4x2(1.0)), vec4(1.0), mat3(1.0), 16));
 uint subgroup_local_id = gl_SubgroupInvocationID;
 uint num_workgroup = gl_NumWorkGroups.x;
 uint workgroup_size = gl_WorkGroupSize.x;
 uint workgroup_id = gl_WorkGroupID.x;
 uint workgroup_base = workgroup_size * workgroup_id;
 uint virtual_gid = workgroup_base + subgroup_id * _GLF_struct_replacement_2._f1.subgroup_size + subgroup_local_id;
 uint next_virtual_gid = workgroup_base + subgroup_id * _GLF_struct_replacement_2._f1.subgroup_size + ((subgroup_local_id + 1) % _GLF_struct_replacement_2._f1.subgroup_size);
 buf[virtual_gid] = 1;
 buf[next_virtual_gid] = 2;
}
