#version 460
struct _GLF_struct_5 {
 ivec2 _f0;
} ;

struct _GLF_struct_6 {
 uvec2 _f0;
 _GLF_struct_5 _f1;
 mat3x2 _f2;
} ;

struct _GLF_struct_4 {
 int _f0;
} ;

struct _GLF_struct_2 {
 float _f0;
} ;

struct _GLF_struct_1 {
 mat3x2 _f0;
 mat3 _f1;
 mat2x4 _f2;
 uvec2 _f3;
 mat4x2 _f4;
 mat2x4 _f5;
 uint workgroup_size;
 uvec4 _f6;
} ;

struct _GLF_struct_3 {
 _GLF_struct_1 _f0;
 _GLF_struct_2 _f1;
} ;

struct _GLF_struct_7 {
 _GLF_struct_3 _f0;
 _GLF_struct_4 _f1;
 ivec3 _f2;
 _GLF_struct_6 _f3;
} ;

struct _GLF_struct_0 {
 uint subgroup_id;
 uvec4 _f0;
} ;

layout(set = 0, binding = 0) uniform buf0 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 _GLF_struct_0 _GLF_struct_replacement_0 = _GLF_struct_0(gl_SubgroupID, uvec4(1u));
 uint subgroup_size = gl_SubgroupSize;
 uint gid = gl_GlobalInvocationID.x;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 uint num_workgroup = gl_NumWorkGroups.x;
 _GLF_struct_7 _GLF_struct_replacement_7 = _GLF_struct_7(_GLF_struct_3(_GLF_struct_1(mat3x2(1.0), mat3(1.0), mat2x4(1.0), uvec2(1u), mat4x2(1.0), mat2x4(1.0), gl_WorkGroupSize.x, uvec4(1u)), _GLF_struct_2(1.0)), _GLF_struct_4(1), ivec3(1), _GLF_struct_6(uvec2(1u), _GLF_struct_5(ivec2(1)), mat3x2(1.0)));
 uint total_threads = num_workgroup * _GLF_struct_replacement_7._f0._f0.workgroup_size;
 buf[gid] = 1;
 if(subgroup_local_id + 1 < subgroup_size)
  {
   int i = 0;
   buf[(gid + 1) % total_threads] = 2;
  }
 else
  {
   buf[(gid + 1) % total_threads] = 2;
  }
}
