#version 460
layout(set = 0, binding = 1) uniform buf1 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec2 GLF_merged2_0_1_3_1_1_17gidsubgroup_local_id;
 uint subgroup_id = gl_SubgroupID;
 uint subgroup_size = gl_SubgroupSize;
 uint gid = gl_GlobalInvocationID.x;
 GLF_merged2_0_1_3_1_1_17gidsubgroup_local_id.x = gid;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 GLF_merged2_0_1_3_1_1_17gidsubgroup_local_id.y = subgroup_local_id;
 buf[GLF_merged2_0_1_3_1_1_17gidsubgroup_local_id.x] = 1;
 if(GLF_merged2_0_1_3_1_1_17gidsubgroup_local_id.y + 1 < subgroup_size)
  {
   buf[GLF_merged2_0_1_3_1_1_17gidsubgroup_local_id.x + 1] = 2;
  }
 else
  {
   buf[(GLF_merged2_0_1_3_1_1_17gidsubgroup_local_id.x + 1) % subgroup_size] = 2;
  }
}
