#version 460
struct _GLF_struct_24 {
 vec2 _f0;
 mat4x2 _f1;
 mat3x2 _f2;
 mat4 _f3;
 mat2 _f4;
 vec2 _f5;
} ;

struct _GLF_struct_23 {
 vec4 _f0;
 mat2x3 _f1;
} ;

struct _GLF_struct_22 {
 ivec2 _f0;
 bool _f1;
 vec3 _f2;
 vec4 _f3;
 bvec3 _f4;
 bvec2 _f5;
 bool _f6;
} ;

struct _GLF_struct_25 {
 bool _f0;
 _GLF_struct_22 _f1;
 _GLF_struct_23 _f2;
 _GLF_struct_24 _f3;
 vec4 _f4;
} ;

struct _GLF_struct_20 {
 vec2 _f0;
 mat2x4 _f1;
 mat2 _f2;
} ;

struct _GLF_struct_19 {
 ivec2 _f0;
 bvec4 _f1;
 mat4x3 _f2;
 int _f3;
 bool _f4;
 mat2x3 _f5;
 ivec3 _f6;
} ;

struct _GLF_struct_18 {
 mat2x4 _f0;
 bvec2 _f1;
 mat3x4 _f2;
 bvec2 _f3;
 mat4x2 _f4;
 mat3 _f5;
 mat2 _f6;
} ;

struct _GLF_struct_21 {
 int _f0;
 mat4x3 _f1;
 _GLF_struct_18 _f2;
 _GLF_struct_19 _f3;
 mat2 _f4;
 _GLF_struct_20 _f5;
 vec4 _f6;
} ;

struct _GLF_struct_16 {
 bvec3 _f0;
} ;

struct _GLF_struct_15 {
 mat2 _f0;
 mat2x4 _f1;
 mat3x2 _f2;
 mat4 _f3;
 mat3x4 _f4;
 mat2 _f5;
} ;

struct _GLF_struct_14 {
 bvec4 _f0;
 mat3 _f1;
 mat3x2 _f2;
 bvec2 _f3;
 uint _f4;
} ;

struct _GLF_struct_17 {
 _GLF_struct_14 _f0;
 mat3x2 _f1;
 vec4 _f2;
 _GLF_struct_15 _f3;
 _GLF_struct_16 _f4;
} ;

struct _GLF_struct_26 {
 _GLF_struct_17 _f0;
 _GLF_struct_21 _f1;
 _GLF_struct_25 _f2;
 uvec4 _f3;
 uint workgroup_id;
} ;

struct _GLF_struct_11 {
 mat3x2 _f0;
} ;

struct _GLF_struct_12 {
 _GLF_struct_11 _f0;
 uint workgroup_base;
} ;

struct _GLF_struct_9 {
 mat4x2 _f0;
} ;

struct _GLF_struct_8 {
 ivec4 _f0;
} ;

struct _GLF_struct_10 {
 _GLF_struct_8 _f0;
 _GLF_struct_9 _f1;
} ;

struct _GLF_struct_6 {
 mat3x2 _f0;
 int _f1;
 ivec2 _f2;
} ;

struct _GLF_struct_5 {
 bool _f0;
 uvec3 _f1;
 vec2 _f2;
 mat4x3 _f3;
} ;

struct _GLF_struct_4 {
 float _f0;
 mat4x2 _f1;
 ivec3 _f2;
 vec4 _f3;
 bvec3 _f4;
 bool _f5;
 mat3 _f6;
} ;

struct _GLF_struct_7 {
 int _f0;
 _GLF_struct_4 _f1;
 uvec3 _f2;
 vec2 _f3;
 _GLF_struct_5 _f4;
 _GLF_struct_6 _f5;
} ;

struct _GLF_struct_2 {
 mat4x2 _f0;
 bool _f1;
 uint _f2;
 bvec2 _f3;
 mat2x3 _f4;
} ;

struct _GLF_struct_3 {
 uint _f0;
 _GLF_struct_2 _f1;
 uvec2 _f2;
 bvec2 _f3;
} ;

struct _GLF_struct_0 {
 mat2x4 _f0;
 ivec4 _f1;
 int _f2;
} ;

struct _GLF_struct_1 {
 _GLF_struct_0 _f0;
 mat3x4 _f1;
 uint _f2;
 mat2x3 _f3;
} ;

struct _GLF_struct_13 {
 uvec3 _f0;
 _GLF_struct_1 _f1;
 _GLF_struct_3 _f2;
 _GLF_struct_7 _f3;
 bvec3 _f4;
 _GLF_struct_10 _f5;
 _GLF_struct_12 _f6;
} ;

layout(set = 0, binding = 1) uniform buf1 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uint subgroup_id = gl_SubgroupID;
 uint subgroup_size = 16;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 uint num_workgroup = gl_NumWorkGroups.x;
 uint workgroup_size = gl_WorkGroupSize.x;
 _GLF_struct_26 _GLF_struct_replacement_26 = _GLF_struct_26(_GLF_struct_17(_GLF_struct_14(bvec4(true), mat3(1.0), mat3x2(1.0), bvec2(true), 1u), mat3x2(1.0), vec4(1.0), _GLF_struct_15(mat2(1.0), mat2x4(1.0), mat3x2(1.0), mat4(1.0), mat3x4(1.0), mat2(1.0)), _GLF_struct_16(bvec3(true))), _GLF_struct_21(1, mat4x3(1.0), _GLF_struct_18(mat2x4(1.0), bvec2(true), mat3x4(1.0), bvec2(true), mat4x2(1.0), mat3(1.0), mat2(1.0)), _GLF_struct_19(ivec2(1), bvec4(true), mat4x3(1.0), 1, true, mat2x3(1.0), ivec3(1)), mat2(1.0), _GLF_struct_20(vec2(1.0), mat2x4(1.0), mat2(1.0)), vec4(1.0)), _GLF_struct_25(true, _GLF_struct_22(ivec2(1), true, vec3(1.0), vec4(1.0), bvec3(true), bvec2(true), true), _GLF_struct_23(vec4(1.0), mat2x3(1.0)), _GLF_struct_24(vec2(1.0), mat4x2(1.0), mat3x2(1.0), mat4(1.0), mat2(1.0), vec2(1.0)), vec4(1.0)), uvec4(1u), gl_WorkGroupID.x);
 _GLF_struct_13 _GLF_struct_replacement_13 = _GLF_struct_13(uvec3(1u), _GLF_struct_1(_GLF_struct_0(mat2x4(1.0), ivec4(1), 1), mat3x4(1.0), 1u, mat2x3(1.0)), _GLF_struct_3(1u, _GLF_struct_2(mat4x2(1.0), true, 1u, bvec2(true), mat2x3(1.0)), uvec2(1u), bvec2(true)), _GLF_struct_7(1, _GLF_struct_4(1.0, mat4x2(1.0), ivec3(1), vec4(1.0), bvec3(true), true, mat3(1.0)), uvec3(1u), vec2(1.0), _GLF_struct_5(true, uvec3(1u), vec2(1.0), mat4x3(1.0)), _GLF_struct_6(mat3x2(1.0), 1, ivec2(1))), bvec3(true), _GLF_struct_10(_GLF_struct_8(ivec4(1)), _GLF_struct_9(mat4x2(1.0))), _GLF_struct_12(_GLF_struct_11(mat3x2(1.0)), workgroup_size * _GLF_struct_replacement_26.workgroup_id));
 uint virtual_gid = _GLF_struct_replacement_13._f6.workgroup_base + subgroup_id * subgroup_size + subgroup_local_id;
 uint next_virtual_gid = _GLF_struct_replacement_13._f6.workgroup_base + subgroup_id * subgroup_size + ((subgroup_local_id + 1) % subgroup_size);
 buf[virtual_gid] = 1;
 if(subgroup_local_id + 1 < subgroup_size)
  {
   atomicStore(buf[next_virtual_gid], uint(2), 4, 64, 0);
   subgroupAll(false);
  }
 else
  {
   atomicStore(buf[next_virtual_gid], uint(2), 4, 64, 0);
   subgroupAll(true);
  }
}
