#version 460

#ifndef REDUCER
#define _GLF_ZERO(X, Y)                   (Y)
#define _GLF_ONE(X, Y)                    (Y)
#define _GLF_FALSE(X, Y)                  (Y)
#define _GLF_TRUE(X, Y)                   (Y)
#define _GLF_IDENTITY(X, Y)               (Y)
#define _GLF_DEAD(X)                      (X)
#define _GLF_FUZZED(X)                    (X)
#define _GLF_WRAPPED_LOOP(X)              X
#define _GLF_WRAPPED_IF_TRUE(X)           X
#define _GLF_WRAPPED_IF_FALSE(X)          X
#define _GLF_SWITCH(X)                    X
#define _GLF_MAKE_IN_BOUNDS_INT(IDX, SZ)  clamp(IDX, 0, SZ - 1)
#define _GLF_MAKE_IN_BOUNDS_UINT(IDX, SZ) clamp(IDX, 0u, SZ - 1u)
#endif


struct _GLF_struct_5 {
 vec2 _f0;
 mat4x2 _f1;
 mat2 _f2;
 mat2 _f3;
} ;

struct _GLF_struct_4 {
 ivec3 _f0;
 uvec4 _f1;
 mat2x4 _f2;
 uint _f3;
} ;

struct _GLF_struct_3 {
 vec3 _f0;
 vec3 _f1;
 vec2 _f2;
 mat2x3 _f3;
 uvec4 _f4;
 ivec2 _f5;
 bvec4 _f6;
} ;

struct _GLF_struct_6 {
 mat2x4 _f0;
 _GLF_struct_3 _f1;
 ivec3 _f2;
 _GLF_struct_4 _f3;
 _GLF_struct_5 _f4;
} ;

struct _GLF_struct_1 {
 float _f0;
 uvec3 _f1;
 uvec3 _f2;
 mat3 _f3;
 ivec2 _f4;
 int _f5;
 vec3 _f6;
} ;

struct _GLF_struct_0 {
 mat3x4 _f0;
 mat2x4 _f1;
 vec3 _f2;
 mat4x2 _f3;
 mat3 _f4;
 vec3 _f5;
 uvec2 _f6;
} ;

struct _GLF_struct_2 {
 uvec4 _f0;
 _GLF_struct_0 _f1;
 _GLF_struct_1 _f2;
} ;

struct _GLF_struct_7 {
 uint subgroup_size;
 _GLF_struct_2 _f0;
 mat4x2 _f1;
 _GLF_struct_6 _f2;
} ;

layout(set = 0, binding = 0) uniform buf0 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec3 GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid;
 uvec4 GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base;
 uvec3 GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_base;
 GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz = GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_base;
 uvec2 GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_id;
 GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.xy = GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_id;
 uint subgroup_id = gl_SubgroupID;
 GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.xy.x = subgroup_id;
 _GLF_struct_7 _GLF_struct_replacement_7 = _GLF_struct_7(gl_SubgroupSize, _GLF_struct_2(uvec4(1u), _GLF_struct_0(mat3x4(1.0), mat2x4(1.0), vec3(1.0), mat4x2(1.0), mat3(1.0), vec3(1.0), uvec2(1u)), _GLF_struct_1(1.0, uvec3(1u), uvec3(1u), mat3(1.0), ivec2(1), 1, vec3(1.0))), mat4x2(1.0), _GLF_struct_6(mat2x4(1.0), _GLF_struct_3(vec3(1.0), vec3(1.0), vec2(1.0), mat2x3(1.0), uvec4(1u), ivec2(1), bvec4(true)), ivec3(1), _GLF_struct_4(ivec3(1), uvec4(1u), mat2x4(1.0), 1u), _GLF_struct_5(vec2(1.0), mat4x2(1.0), mat2(1.0), mat2(1.0))));
 GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz.x = _GLF_struct_replacement_7.subgroup_size;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.xy.y = subgroup_local_id;
 uint num_workgroup = gl_NumWorkGroups.x;
 uint workgroup_size = gl_WorkGroupSize.x;
 uint workgroup_id = gl_WorkGroupID.x;
 uint workgroup_base = workgroup_size * workgroup_id;
 GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.w = workgroup_base;
 GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz.z = GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.w;
 uint virtual_gid = GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz.z + GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.xy.x * GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz.x + GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.xy.y;
 GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz.y = virtual_gid;
 if(_GLF_DEAD(false))
  barrier();
 uint next_virtual_gid = GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz.z + _GLF_IDENTITY(GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.xy.x, (GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.xy.x) >> 0u) * GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz.x + ((GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.xy.y + 1) % GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz.x);
 GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.z = next_virtual_gid;
 buf[GLF_merged2_0_3_70_3_1_14GLF_merged3_0_1_13_1_1_11_2_1_14subgroup_sizevirtual_gidworkgroup_baseworkgroup_base.xyz.y] = 1;
 if(_GLF_WRAPPED_IF_FALSE(false))
  {
  }
 else
  {
   buf[GLF_merged2_0_2_53_2_1_16GLF_merged2_0_1_11_1_1_17subgroup_idsubgroup_local_idnext_virtual_gid.z] = 2;
  }
}
