#version 460
struct _GLF_struct_5 {
 uvec4 _f0;
 mat3x2 _f1;
 mat2x3 _f2;
 uvec2 _f3;
 vec4 _f4;
} ;

struct _GLF_struct_6 {
 _GLF_struct_5 _f0;
} ;

struct _GLF_struct_7 {
 uint workgroup_size;
 _GLF_struct_6 _f0;
 float _f1;
} ;

struct _GLF_struct_2 {
 uint _f0;
 mat3x2 _f1;
 int _f2;
 mat2x4 _f3;
 vec2 _f4;
} ;

struct _GLF_struct_1 {
 mat4x2 _f0;
 mat3x2 _f1;
 uvec4 _f2;
 uint workgroup_base;
 vec4 _f3;
} ;

struct _GLF_struct_0 {
 uvec3 _f0;
 vec4 _f1;
 mat4x3 _f2;
 ivec3 _f3;
 ivec3 _f4;
 vec4 _f5;
 mat2x4 _f6;
} ;

struct _GLF_struct_3 {
 uvec3 _f0;
 _GLF_struct_0 _f1;
 ivec2 _f2;
 _GLF_struct_1 _f3;
 _GLF_struct_2 _f4;
} ;

struct _GLF_struct_4 {
 ivec3 _f0;
 _GLF_struct_3 _f1;
 mat3x2 _f2;
} ;

layout(set = 0, binding = 0) uniform buf0 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec3 GLF_merged3_0_1_13_1_1_11_2_1_17num_workgroupsubgroup_idsubgroup_local_id;
 uvec4 GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid;
 uvec3 GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_id;
 GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz = GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_id;
 uvec4 GLF_merged4_0_1_16_1_1_13_2_1_17_3_1_11next_virtual_gidnum_workgroupsubgroup_local_idvirtual_gid;
 uint subgroup_id = gl_SubgroupID;
 GLF_merged3_0_1_13_1_1_11_2_1_17num_workgroupsubgroup_idsubgroup_local_id.y = subgroup_id;
 GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz.x = GLF_merged3_0_1_13_1_1_11_2_1_17num_workgroupsubgroup_idsubgroup_local_id.y;
 uint subgroup_size = 16;
 GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz.y = subgroup_size;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 GLF_merged3_0_1_13_1_1_11_2_1_17num_workgroupsubgroup_idsubgroup_local_id.z = subgroup_local_id;
 GLF_merged4_0_1_16_1_1_13_2_1_17_3_1_11next_virtual_gidnum_workgroupsubgroup_local_idvirtual_gid.z = GLF_merged3_0_1_13_1_1_11_2_1_17num_workgroupsubgroup_idsubgroup_local_id.z;
 uint num_workgroup = gl_NumWorkGroups.x;
 GLF_merged3_0_1_13_1_1_11_2_1_17num_workgroupsubgroup_idsubgroup_local_id.x = num_workgroup;
 GLF_merged4_0_1_16_1_1_13_2_1_17_3_1_11next_virtual_gidnum_workgroupsubgroup_local_idvirtual_gid.y = GLF_merged3_0_1_13_1_1_11_2_1_17num_workgroupsubgroup_idsubgroup_local_id.x;
 _GLF_struct_7 _GLF_struct_replacement_7 = _GLF_struct_7(gl_WorkGroupSize.x, _GLF_struct_6(_GLF_struct_5(uvec4(1u), mat3x2(1.0), mat2x3(1.0), uvec2(1u), vec4(1.0))), 1.0);
 uint workgroup_id = gl_WorkGroupID.x;
 GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz.z = workgroup_id;
 _GLF_struct_4 _GLF_struct_replacement_4 = _GLF_struct_4(ivec3(1), _GLF_struct_3(uvec3(1u), _GLF_struct_0(uvec3(1u), vec4(1.0), mat4x3(1.0), ivec3(1), ivec3(1), vec4(1.0), mat2x4(1.0)), ivec2(1), _GLF_struct_1(mat4x2(1.0), mat3x2(1.0), uvec4(1u), _GLF_struct_replacement_7.workgroup_size * GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz.z, vec4(1.0)), _GLF_struct_2(1u, mat3x2(1.0), 1, mat2x4(1.0), vec2(1.0))), mat3x2(1.0));
 uint virtual_gid = _GLF_struct_replacement_4._f1._f3.workgroup_base + GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz.x * GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz.y + GLF_merged4_0_1_16_1_1_13_2_1_17_3_1_11next_virtual_gidnum_workgroupsubgroup_local_idvirtual_gid.z;
 GLF_merged4_0_1_16_1_1_13_2_1_17_3_1_11next_virtual_gidnum_workgroupsubgroup_local_idvirtual_gid.w = virtual_gid;
 uint next_virtual_gid = _GLF_struct_replacement_4._f1._f3.workgroup_base + GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz.x * GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz.y + ((GLF_merged4_0_1_16_1_1_13_2_1_17_3_1_11next_virtual_gidnum_workgroupsubgroup_local_idvirtual_gid.z + 1) % GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.xyz.y);
 GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.w = next_virtual_gid;
 GLF_merged4_0_1_16_1_1_13_2_1_17_3_1_11next_virtual_gidnum_workgroupsubgroup_local_idvirtual_gid.x = GLF_merged2_0_3_68_3_1_16GLF_merged3_0_1_11_1_1_13_2_1_12subgroup_idsubgroup_sizeworkgroup_idnext_virtual_gid.w;
 buf[GLF_merged4_0_1_16_1_1_13_2_1_17_3_1_11next_virtual_gidnum_workgroupsubgroup_local_idvirtual_gid.w] = 1;
 atomicStore(buf[GLF_merged4_0_1_16_1_1_13_2_1_17_3_1_11next_virtual_gidnum_workgroupsubgroup_local_idvirtual_gid.x], uint(2), 4, 64, 0);
}
