#version 460
layout(set = 0, binding = 0) uniform buf0 {
 vec2 injectionSwitch;
};
struct _GLF_struct_0 {
 ivec3 _f0;
 uint gid;
} ;

#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uint subgroup_id = gl_SubgroupID;
 uint subgroup_size = gl_SubgroupSize;
 _GLF_struct_0 _GLF_struct_replacement_0 = _GLF_struct_0(ivec3(1), gl_GlobalInvocationID.x);
 uint subgroup_local_id = gl_SubgroupInvocationID;
 uint num_workgroup = gl_NumWorkGroups.x;
 uint workgroup_size = gl_WorkGroupSize.x;
 uint total_threads = num_workgroup * workgroup_size;
 buf[_GLF_struct_replacement_0.gid] = 1;
 if(subgroup_local_id + 1 < subgroup_size)
  {
   int i = 0;
   atomicStore(buf[(_GLF_struct_replacement_0.gid + 1) % total_threads], uint(2), 4, 64, 4);
  }
 else
  {
   atomicStore(buf[(_GLF_struct_replacement_0.gid + 1) % total_threads], uint(2), 4, 64, 4);
  }
}
