#version 460

#ifndef REDUCER
#define _GLF_ZERO(X, Y)                   (Y)
#define _GLF_ONE(X, Y)                    (Y)
#define _GLF_FALSE(X, Y)                  (Y)
#define _GLF_TRUE(X, Y)                   (Y)
#define _GLF_IDENTITY(X, Y)               (Y)
#define _GLF_DEAD(X)                      (X)
#define _GLF_FUZZED(X)                    (X)
#define _GLF_WRAPPED_LOOP(X)              X
#define _GLF_WRAPPED_IF_TRUE(X)           X
#define _GLF_WRAPPED_IF_FALSE(X)          X
#define _GLF_SWITCH(X)                    X
#define _GLF_MAKE_IN_BOUNDS_INT(IDX, SZ)  clamp(IDX, 0, SZ - 1)
#define _GLF_MAKE_IN_BOUNDS_UINT(IDX, SZ) clamp(IDX, 0u, SZ - 1u)
#endif


struct _GLF_struct_24 {
 uint workgroup_size;
 bvec4 _f0;
} ;

struct _GLF_struct_21 {
 bool _f0;
 uvec3 _f1;
 uvec2 _f2;
 mat2x4 _f3;
} ;

struct _GLF_struct_20 {
 mat4x2 _f0;
 mat2x4 _f1;
 mat2x4 _f2;
 uvec3 _f3;
 uint _f4;
 vec4 _f5;
} ;

struct _GLF_struct_22 {
 vec4 _f0;
 _GLF_struct_20 _f1;
 _GLF_struct_21 _f2;
} ;

struct _GLF_struct_23 {
 _GLF_struct_22 _f0;
 uint next_virtual_gid;
} ;

struct _GLF_struct_17 {
 vec2 _f0;
 mat3 _f1;
} ;

struct _GLF_struct_16 {
 mat4x3 _f0;
 uint _f1;
 uvec4 _f2;
 ivec3 _f3;
 ivec3 _f4;
 mat3x4 _f5;
} ;

struct _GLF_struct_15 {
 float _f0;
} ;

struct _GLF_struct_14 {
 vec2 _f0;
 bvec4 _f1;
} ;

struct _GLF_struct_18 {
 mat3x4 _f0;
 _GLF_struct_14 _f1;
 ivec2 _f2;
 _GLF_struct_15 _f3;
 mat2 _f4;
 _GLF_struct_16 _f5;
 _GLF_struct_17 _f6;
} ;

struct _GLF_struct_12 {
 uvec4 _f0;
 ivec4 _f1;
 ivec4 _f2;
 float _f3;
 mat2x4 _f4;
 mat2x3 _f5;
} ;

struct _GLF_struct_11 {
 vec3 _f0;
} ;

struct _GLF_struct_10 {
 mat4x2 _f0;
 mat2 _f1;
} ;

struct _GLF_struct_9 {
 mat3x2 _f0;
 mat4 _f1;
 vec4 _f2;
 mat2x4 _f3;
 mat3 _f4;
 bvec3 _f5;
 ivec4 _f6;
} ;

struct _GLF_struct_13 {
 uint subgroup_id;
 _GLF_struct_9 _f0;
 _GLF_struct_10 _f1;
 _GLF_struct_11 _f2;
 mat2x4 _f3;
 _GLF_struct_12 _f4;
 uvec4 _f5;
 mat3 _f6;
} ;

struct _GLF_struct_7 {
 vec2 _f0;
 uvec2 _f1;
 int _f2;
 mat2 _f3;
 mat4x3 _f4;
} ;

struct _GLF_struct_6 {
 mat3x2 _f0;
 vec2 _f1;
 int _f2;
} ;

struct _GLF_struct_5 {
 mat2x4 _f0;
 mat2x4 _f1;
 mat3 _f2;
 mat2x4 _f3;
 mat2x3 _f4;
} ;

struct _GLF_struct_4 {
 mat4x2 _f0;
 bvec2 _f1;
 uvec4 _f2;
 mat4x2 _f3;
 vec4 _f4;
} ;

struct _GLF_struct_8 {
 _GLF_struct_4 _f0;
 _GLF_struct_5 _f1;
 _GLF_struct_6 _f2;
 vec4 _f3;
 _GLF_struct_7 _f4;
 uvec2 _f5;
 mat2x3 _f6;
} ;

struct _GLF_struct_19 {
 _GLF_struct_8 _f0;
 mat2x3 _f1;
 _GLF_struct_13 _f2;
 _GLF_struct_18 _f3;
} ;

struct _GLF_struct_1 {
 mat4 _f0;
 ivec4 _f1;
 uvec4 _f2;
 float _f3;
 bool _f4;
 vec3 _f5;
} ;

struct _GLF_struct_0 {
 mat3x2 _f0;
} ;

struct _GLF_struct_2 {
 _GLF_struct_0 _f0;
 _GLF_struct_1 _f1;
 vec4 _f2;
} ;

struct _GLF_struct_3 {
 mat3 _f0;
 int _f1;
 bvec4 _f2;
 uint workgroup_base;
 _GLF_struct_2 _f3;
} ;

layout(set = 0, binding = 0) uniform buf0 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 _GLF_struct_19 _GLF_struct_replacement_19 = _GLF_struct_19(_GLF_struct_8(_GLF_struct_4(mat4x2(1.0), bvec2(true), uvec4(1u), mat4x2(1.0), vec4(1.0)), _GLF_struct_5(mat2x4(1.0), mat2x4(1.0), mat3(1.0), mat2x4(1.0), mat2x3(1.0)), _GLF_struct_6(mat3x2(1.0), vec2(1.0), 1), vec4(1.0), _GLF_struct_7(vec2(1.0), uvec2(1u), 1, mat2(1.0), mat4x3(1.0)), uvec2(1u), mat2x3(1.0)), mat2x3(1.0), _GLF_struct_13(gl_SubgroupID, _GLF_struct_9(mat3x2(1.0), mat4(1.0), vec4(1.0), mat2x4(1.0), mat3(1.0), bvec3(true), ivec4(1)), _GLF_struct_10(mat4x2(1.0), mat2(1.0)), _GLF_struct_11(vec3(1.0)), mat2x4(1.0), _GLF_struct_12(uvec4(1u), ivec4(1), ivec4(1), 1.0, mat2x4(1.0), mat2x3(1.0)), uvec4(1u), mat3(1.0)), _GLF_struct_18(mat3x4(1.0), _GLF_struct_14(vec2(1.0), bvec4(true)), ivec2(1), _GLF_struct_15(1.0), mat2(1.0), _GLF_struct_16(mat4x3(1.0), 1u, uvec4(1u), ivec3(1), ivec3(1), mat3x4(1.0)), _GLF_struct_17(vec2(1.0), mat3(1.0))));
 if(_GLF_DEAD(_GLF_FALSE(false, (injectionSwitch.x > injectionSwitch.y))))
  return;
 uint subgroup_size = gl_SubgroupSize;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 uint num_workgroup = gl_NumWorkGroups.x;
 _GLF_struct_24 _GLF_struct_replacement_24 = _GLF_struct_24(gl_WorkGroupSize.x, bvec4(true));
 if(_GLF_DEAD(_GLF_IDENTITY(false, true && (false))))
  return;
 if(_GLF_DEAD(false))
  return;
 uint workgroup_id = gl_WorkGroupID.x;
 _GLF_struct_3 _GLF_struct_replacement_3 = _GLF_struct_3(mat3(1.0), 1, bvec4(true), _GLF_struct_replacement_24.workgroup_size * workgroup_id, _GLF_struct_2(_GLF_struct_0(mat3x2(1.0)), _GLF_struct_1(mat4(1.0), ivec4(1), uvec4(1u), 1.0, true, vec3(1.0)), vec4(1.0)));
 if(_GLF_DEAD(false))
  return;
 uint virtual_gid = _GLF_struct_replacement_3.workgroup_base + _GLF_struct_replacement_19._f2.subgroup_id * subgroup_size + subgroup_local_id;
 _GLF_struct_23 _GLF_struct_replacement_23 = _GLF_struct_23(_GLF_struct_22(vec4(1.0), _GLF_struct_20(mat4x2(1.0), mat2x4(1.0), mat2x4(1.0), uvec3(1u), 1u, vec4(1.0)), _GLF_struct_21(true, uvec3(1u), uvec2(1u), mat2x4(1.0))), _GLF_struct_replacement_3.workgroup_base + _GLF_struct_replacement_19._f2.subgroup_id * subgroup_size + ((subgroup_local_id + 1) % subgroup_size));
 if(_GLF_DEAD(_GLF_FALSE(false, (injectionSwitch.x > injectionSwitch.y))))
  return;
 buf[virtual_gid] = 1;
 if(_GLF_DEAD(false))
  return;
 if(subgroup_local_id + 1 < subgroup_size)
  {
   int i = 0;
   atomicStore(buf[_GLF_struct_replacement_23.next_virtual_gid], uint(2), 4, 64, 4);
  }
 else
  {
   atomicStore(buf[_GLF_struct_replacement_23.next_virtual_gid], uint(2), 4, 64, 4);
  }
}
