#version 460
struct _GLF_struct_21 {
 uvec4 _f0;
 vec2 _f1;
} ;

struct _GLF_struct_19 {
 mat4x3 _f0;
 uint _f1;
} ;

struct _GLF_struct_20 {
 _GLF_struct_19 _f0;
 mat4 _f1;
 ivec3 _f2;
 uvec2 GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_size;
 mat4 _f3;
} ;

struct _GLF_struct_22 {
 _GLF_struct_20 _f0;
 mat2x3 _f1;
 _GLF_struct_21 _f2;
} ;

struct _GLF_struct_16 {
 int _f0;
 uvec2 _f1;
 mat4 _f2;
 mat3x2 _f3;
} ;

struct _GLF_struct_15 {
 mat2x4 _f0;
 mat2x3 _f1;
 bool _f2;
 mat3x2 _f3;
 mat2 _f4;
 mat3x4 _f5;
 mat3x4 _f6;
} ;

struct _GLF_struct_14 {
 ivec3 _f0;
 mat3 _f1;
 uvec2 _f2;
 mat4x3 _f3;
 bvec3 _f4;
} ;

struct _GLF_struct_17 {
 mat4x2 _f0;
 bool _f1;
 _GLF_struct_14 _f2;
 _GLF_struct_15 _f3;
 _GLF_struct_16 _f4;
} ;

struct _GLF_struct_12 {
 mat3 _f0;
 mat3x2 _f1;
 bool _f2;
} ;

struct _GLF_struct_11 {
 mat2x3 _f0;
 bool _f1;
 mat2x4 _f2;
 mat3 _f3;
 mat3x4 _f4;
 bvec3 _f5;
 ivec2 _f6;
} ;

struct _GLF_struct_13 {
 uint _f0;
 _GLF_struct_11 _f1;
 _GLF_struct_12 _f2;
} ;

struct _GLF_struct_18 {
 uint virtual_gid;
 _GLF_struct_13 _f0;
 _GLF_struct_17 _f1;
} ;

struct _GLF_struct_8 {
 bool _f0;
 ivec4 _f1;
 vec2 _f2;
 mat4x3 _f3;
 float _f4;
 ivec4 _f5;
} ;

struct _GLF_struct_7 {
 mat3 _f0;
 mat4x2 _f1;
 uint _f2;
 ivec2 _f3;
 uvec4 _f4;
} ;

struct _GLF_struct_6 {
 mat2x4 _f0;
 vec2 _f1;
} ;

struct _GLF_struct_5 {
 uvec3 _f0;
 bvec3 _f1;
 mat4x3 _f2;
 vec3 _f3;
 mat2x4 _f4;
 vec4 _f5;
 mat3 _f6;
} ;

struct _GLF_struct_4 {
 mat3 _f0;
 uvec2 _f1;
 uvec4 _f2;
 uvec4 _f3;
 mat3x2 _f4;
 vec3 _f5;
} ;

struct _GLF_struct_9 {
 _GLF_struct_4 _f0;
 _GLF_struct_5 _f1;
 _GLF_struct_6 _f2;
 _GLF_struct_7 _f3;
 uint workgroup_base;
 _GLF_struct_8 _f4;
} ;

struct _GLF_struct_3 {
 mat2 _f0;
 mat2x4 _f1;
} ;

struct _GLF_struct_10 {
 mat4 _f0;
 vec4 _f1;
 int _f2;
 _GLF_struct_3 _f3;
 vec2 _f4;
 mat3x2 _f5;
 _GLF_struct_9 _f6;
} ;

struct _GLF_struct_2 {
 vec3 _f0;
 uvec2 GLF_merged2_0_1_17_1_1_14subgroup_local_idworkgroup_base;
} ;

struct _GLF_struct_0 {
 uint subgroup_local_id;
 mat4 _f0;
} ;

struct _GLF_struct_1 {
 _GLF_struct_0 _f0;
 ivec2 _f1;
} ;

layout(set = 0, binding = 0) uniform buf0 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec4 GLF_merged2_0_3_70_3_1_11GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_basesubgroup_id;
 uvec4 GLF_merged2_0_2_50_2_2_51GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizeGLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id;
 uvec2 GLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id;
 GLF_merged2_0_2_50_2_2_51GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizeGLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id.zw = GLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id;
 uvec4 GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid;
 _GLF_struct_22 _GLF_struct_replacement_22;
 GLF_merged2_0_2_50_2_2_51GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizeGLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id.xy = _GLF_struct_replacement_22._f0.GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_size;
 GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.xy = GLF_merged2_0_2_50_2_2_51GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizeGLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id.xy;
 uvec3 GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_base;
 GLF_merged2_0_3_70_3_1_11GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_basesubgroup_id.xyz = GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_base;
 _GLF_struct_2 _GLF_struct_replacement_2;
 uint subgroup_id = gl_SubgroupID;
 GLF_merged2_0_3_70_3_1_11GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_basesubgroup_id.w = subgroup_id;
 GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.xy.x = GLF_merged2_0_3_70_3_1_11GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_basesubgroup_id.w;
 uint subgroup_size = gl_SubgroupSize;
 _GLF_struct_1 _GLF_struct_replacement_1 = _GLF_struct_1(_GLF_struct_0(gl_SubgroupInvocationID, mat4(1.0)), ivec2(1));
 _GLF_struct_replacement_2.GLF_merged2_0_1_17_1_1_14subgroup_local_idworkgroup_base.x = _GLF_struct_replacement_1._f0.subgroup_local_id;
 uint num_workgroup = gl_NumWorkGroups.x;
 GLF_merged2_0_3_70_3_1_11GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_basesubgroup_id.xyz.x = num_workgroup;
 uint workgroup_size = gl_WorkGroupSize.x;
 GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.xy.y = workgroup_size;
 uint workgroup_id = gl_WorkGroupID.x;
 GLF_merged2_0_2_50_2_2_51GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizeGLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id.zw.y = workgroup_id;
 _GLF_struct_10 _GLF_struct_replacement_10 = _GLF_struct_10(mat4(1.0), vec4(1.0), 1, _GLF_struct_3(mat2(1.0), mat2x4(1.0)), vec2(1.0), mat3x2(1.0), _GLF_struct_9(_GLF_struct_4(mat3(1.0), uvec2(1u), uvec4(1u), uvec4(1u), mat3x2(1.0), vec3(1.0)), _GLF_struct_5(uvec3(1u), bvec3(true), mat4x3(1.0), vec3(1.0), mat2x4(1.0), vec4(1.0), mat3(1.0)), _GLF_struct_6(mat2x4(1.0), vec2(1.0)), _GLF_struct_7(mat3(1.0), mat4x2(1.0), 1u, ivec2(1), uvec4(1u)), GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.xy.y * GLF_merged2_0_2_50_2_2_51GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizeGLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id.zw.y, _GLF_struct_8(true, ivec4(1), vec2(1.0), mat4x3(1.0), 1.0, ivec4(1))));
 GLF_merged2_0_2_50_2_2_51GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizeGLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id.zw.x = _GLF_struct_replacement_10._f6.workgroup_base;
 GLF_merged2_0_3_70_3_1_11GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_basesubgroup_id.xyz.z = GLF_merged2_0_2_50_2_2_51GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizeGLF_merged2_0_1_14_1_1_12workgroup_baseworkgroup_id.zw.x;
 _GLF_struct_replacement_2.GLF_merged2_0_1_17_1_1_14subgroup_local_idworkgroup_base.y = GLF_merged2_0_3_70_3_1_11GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_basesubgroup_id.xyz.z;
 _GLF_struct_18 _GLF_struct_replacement_18 = _GLF_struct_18(_GLF_struct_replacement_2.GLF_merged2_0_1_17_1_1_14subgroup_local_idworkgroup_base.y + GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.xy.x * subgroup_size + _GLF_struct_replacement_2.GLF_merged2_0_1_17_1_1_14subgroup_local_idworkgroup_base.x, _GLF_struct_13(1u, _GLF_struct_11(mat2x3(1.0), true, mat2x4(1.0), mat3(1.0), mat3x4(1.0), bvec3(true), ivec2(1)), _GLF_struct_12(mat3(1.0), mat3x2(1.0), true)), _GLF_struct_17(mat4x2(1.0), true, _GLF_struct_14(ivec3(1), mat3(1.0), uvec2(1u), mat4x3(1.0), bvec3(true)), _GLF_struct_15(mat2x4(1.0), mat2x3(1.0), true, mat3x2(1.0), mat2(1.0), mat3x4(1.0), mat3x4(1.0)), _GLF_struct_16(1, uvec2(1u), mat4(1.0), mat3x2(1.0))));
 GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.w = _GLF_struct_replacement_18.virtual_gid;
 GLF_merged2_0_3_70_3_1_11GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_basesubgroup_id.xyz.y = GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.w;
 uint next_virtual_gid = _GLF_struct_replacement_2.GLF_merged2_0_1_17_1_1_14subgroup_local_idworkgroup_base.y + GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.xy.x * subgroup_size + ((_GLF_struct_replacement_2.GLF_merged2_0_1_17_1_1_14subgroup_local_idworkgroup_base.x + 1) % subgroup_size);
 GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.z = next_virtual_gid;
 buf[GLF_merged2_0_3_70_3_1_11GLF_merged3_0_1_13_1_1_11_2_1_14num_workgroupvirtual_gidworkgroup_basesubgroup_id.xyz.y] = 1;
 if(_GLF_struct_replacement_2.GLF_merged2_0_1_17_1_1_14subgroup_local_idworkgroup_base.x + 1 < subgroup_size)
  {
   atomicStore(buf[GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.z], uint(2), 4, 64, 0);
   subgroupAll(false);
  }
 else
  {
   atomicStore(buf[GLF_merged3_0_2_50_2_1_16_3_1_11GLF_merged2_0_1_11_1_1_14subgroup_idworkgroup_sizenext_virtual_gidvirtual_gid.z], uint(2), 4, 64, 0);
   subgroupAll(true);
  }
}
