#version 460

#ifndef REDUCER
#define _GLF_ZERO(X, Y)                   (Y)
#define _GLF_ONE(X, Y)                    (Y)
#define _GLF_FALSE(X, Y)                  (Y)
#define _GLF_TRUE(X, Y)                   (Y)
#define _GLF_IDENTITY(X, Y)               (Y)
#define _GLF_DEAD(X)                      (X)
#define _GLF_FUZZED(X)                    (X)
#define _GLF_WRAPPED_LOOP(X)              X
#define _GLF_WRAPPED_IF_TRUE(X)           X
#define _GLF_WRAPPED_IF_FALSE(X)          X
#define _GLF_SWITCH(X)                    X
#define _GLF_MAKE_IN_BOUNDS_INT(IDX, SZ)  clamp(IDX, 0, SZ - 1)
#define _GLF_MAKE_IN_BOUNDS_UINT(IDX, SZ) clamp(IDX, 0u, SZ - 1u)
#endif


struct _GLF_struct_9 {
 ivec2 _f0;
 bvec4 _f1;
 mat3x4 _f2;
 mat2x3 _f3;
 bvec2 _f4;
 mat4x2 _f5;
 vec4 _f6;
} ;

struct _GLF_struct_10 {
 vec2 _f0;
 _GLF_struct_9 _f1;
 vec3 _f2;
} ;

struct _GLF_struct_8 {
 int _f0;
 int _f1;
 mat3 _f2;
} ;

struct _GLF_struct_6 {
 int _f0;
 uint _f1;
 vec3 _f2;
 ivec2 _f3;
 uvec2 _f4;
 vec2 _f5;
 bvec2 _f6;
} ;

struct _GLF_struct_5 {
 uvec3 _f0;
 vec4 _f1;
} ;

struct _GLF_struct_4 {
 vec4 _f0;
 float _f1;
} ;

struct _GLF_struct_3 {
 bvec3 _f0;
} ;

struct _GLF_struct_7 {
 _GLF_struct_3 _f0;
 _GLF_struct_4 _f1;
 _GLF_struct_5 _f2;
 _GLF_struct_6 _f3;
} ;

struct _GLF_struct_1 {
 bvec4 _f0;
 ivec2 _f1;
 uvec2 _f2;
} ;

struct _GLF_struct_2 {
 _GLF_struct_1 _f0;
} ;

struct _GLF_struct_11 {
 _GLF_struct_2 _f0;
 mat2x3 _f1;
 _GLF_struct_7 _f2;
 _GLF_struct_8 _f3;
 _GLF_struct_10 _f4;
 bool _f5;
 uint num_workgroup;
 uint _f6;
} ;

struct _GLF_struct_0 {
 uint subgroup_local_id;
 mat4x3 _f0;
 bvec4 _f1;
 mat2x3 _f2;
} ;

layout(set = 0, binding = 0) uniform buf0 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uint subgroup_id = gl_SubgroupID;
 uint subgroup_size = gl_SubgroupSize;
 _GLF_struct_0 _GLF_struct_replacement_0 = _GLF_struct_0(gl_SubgroupInvocationID, mat4x3(1.0), bvec4(true), mat2x3(1.0));
 if(_GLF_DEAD(_GLF_FALSE(false, (injectionSwitch.x > injectionSwitch.y))))
  barrier();
 _GLF_struct_11 _GLF_struct_replacement_11 = _GLF_struct_11(_GLF_struct_2(_GLF_struct_1(bvec4(true), ivec2(1), uvec2(1u))), mat2x3(1.0), _GLF_struct_7(_GLF_struct_3(bvec3(true)), _GLF_struct_4(vec4(1.0), 1.0), _GLF_struct_5(uvec3(1u), vec4(1.0)), _GLF_struct_6(1, 1u, vec3(1.0), ivec2(1), uvec2(1u), vec2(1.0), bvec2(true))), _GLF_struct_8(1, 1, mat3(1.0)), _GLF_struct_10(vec2(1.0), _GLF_struct_9(ivec2(1), bvec4(true), mat3x4(1.0), mat2x3(1.0), bvec2(true), mat4x2(1.0), vec4(1.0)), vec3(1.0)), true, gl_NumWorkGroups.x, 1u);
 if(_GLF_DEAD(_GLF_IDENTITY(false, bool(bvec2(false, false)))))
  barrier();
 uint workgroup_size = gl_WorkGroupSize.x;
 uint workgroup_id = gl_WorkGroupID.x;
 uint workgroup_base = workgroup_size * workgroup_id;
 uint virtual_gid = workgroup_base + subgroup_id * subgroup_size + _GLF_struct_replacement_0.subgroup_local_id;
 uint next_virtual_gid = workgroup_base + subgroup_id * subgroup_size + ((_GLF_struct_replacement_0.subgroup_local_id + 1) % subgroup_size);
 buf[virtual_gid] = 1;
 if(_GLF_struct_replacement_0.subgroup_local_id + 1 < subgroup_size)
  {
   atomicStore(buf[next_virtual_gid], uint(2), 4, 64, 0);
   if(_GLF_DEAD(false))
    barrier();
   subgroupAll(false);
  }
 else
  {
   atomicStore(buf[next_virtual_gid], uint(2), 4, 64, 0);
   subgroupAll(true);
  }
}
